### ISSUE TITLE
Can't apply to android libraries

### ISSUE THREAD

**Issue by ouchadam** [novoda/sqlite-analyzer#35]
The plugin assumes there are `applicationVariants`  https://github.com/novoda/sqlite-analyzer/blob/37c6d64597bb67265e317ed2febb7aed09f46b29/analyzer/src/main/groovy/com/novoda/sqlite/generator/SqliteAnalyzerPlugin.groovy#L11 which is not the case for android libraries 

`Error:Could not find property 'applicationVariants' on com.android.build.gradle.LibraryExtension_Decorated@6f742874.`

**Comment by devisnik** [comment]
:+1: Thanks for reporting.

**Comment by ouchadam** [comment]
this has been fixed in the master branch, any plans for a release?
