### ISSUE TITLE
Generated get/setters don't use generated names constants

### ISSUE THREAD

**Issue by rock3r** [novoda/sqlite-analyzer#46]
When you look at the code generated by this tool, you notice that the getters and setters look like this:

``` java
    public static int getId(android.database.Cursor cursor) {
        int index = cursor.getColumnIndexOrThrow("_id");
        return cursor.getInt(index);
    }

    public static void setId(int value, android.content.ContentValues values) {
        values.put("_id", value);
    }
```

They're using hardcoded strings to address the columns instead of using the corrects constants that are available in `DB.Columns.[TableName]`.

**Comment by devisnik** [comment]
Why would you classify it as a bug?
Is this causing any misbehaviour? Or is it for readability / style reasons only?

**Comment by friedger** [comment]
Using a string save you one lookup

**Comment by rock3r** [comment]
@devisnik it’s not misbehaving as far as I can tell, but it’s weird seeing raw strings around when you have the constants in the same file. Using the constants would also make it easier to avoid issues and to track where stuff is used when doing a find usages

@friedger wat
