### ISSUE TITLE
View accessors assume nullable

### ISSUE THREAD

**Issue by fourlastor** [novoda/sqlite-analyzer#47]
When you create a table with a `NOT NULL` field and a view on that table

E.g.:

``` sql
CREATE TABLE 'book' (
  book_number INTEGER NOT NULL
)

CREATE VIEW 'book_view' AS SELECT * FROM book;
```

The generated `BookView.getBookNumber(cursor)` is actually using boxed primitives and checking for null (and returning null if `cursor.isNull(index)` is true, which is never going to be the case) while the class `Book.getBookNumber(cursor)` is returning an `int` as expected.

**Comment by devisnik** [comment]
We currently use the sql query `"PRAGMA table_info('"<table/view name>"');"` to determine the column data of a given table or view. It seems that the nullability information of the collumns is not available for views via this query.

**Comment by devisnik** [comment]
We can actually analyze the `ResultSetMetaData` of  a query like `"select * from <table name> LIMIT 0"`. That way we'd be able to determine the table name of a column, even when querying on a view. We could then read the nullability info from the table. Would only work as long as the column name is not changed though.

**Comment by fourlastor** [comment]
Hm I start to see why it's reported as nullable.

The point is that the _table column_ is not null, but the _view column_ might as well be, e.g.:

```sql
CREATE VIEW `this_is_a_view` AS
SELECT b_table.not_null_column FROM a_table LEFT JOIN b_table
ON a_table.id = b_table.a_id
```

If you don't have an entry for `a_id` then you'll have a null field there.

**Comment by devisnik** [comment]
Good points. Wonder how to go about this now. Any idea?

**Comment by fourlastor** [comment]
Didn't have the time to think about a solution, let's see next mid-week?

**Comment by fourlastor** [comment]
I guess the main point is that we can get only so much info from the DB, and that's making things harder (see also long/int problems).

Maybe a step forward is to do something similar to autovalue: declare an abstract class that represents your model and let the plugin generate the implementation for it. That way you could have:

```java
@SqliteTable
abstract class BookTable {
    String title();
    Integer usersWhoLikedIt(); // I am nullable!
    long timestamp(); // I am long!
}
```

That also means you don't generate getters/setters for fields which are just used internally (e.g. for joins) and could save some methods which is always a blessing in Android.
