### ISSUE TITLE
Sorting of migration files too specific

### ISSUE THREAD

**Issue by mattijsf** [novoda/sqlite-analyzer#51]
We have been using this code generator for quite a while now. We have been using the following filename convention:

`app.db_upgrade_<oldversion>_<newversion>.sql` 

One could argue if that is a sensible name but thats where we ended up with some time ago and it worked fine. Until travis decided to update their images with updated os / java. 

After investigation it turned out that since the travis update the migration files where executed in the wrong order.

I tracked it down to:
https://github.com/novoda/sqlite-analyzer/blob/0.3.2/analyzer/src/main/java/com/novoda/sqlite/NumberedFilesComparator.java

Which assumes that the migration files are prefixed with `<number>_`. In our case the mentioned comparator would always return 0 and thus rely on the order of `File.listFiles()` which is not deterministic and results might have changed due to OS / openjdk vs oraclejdk  / java version changes.

I think its good that users should to be aware of this requirement. We renamed the files now. But a more logical comparator would be better I think.

**Comment by ouchadam** [comment]
completely agree that this should be made known 👍 

Perhaps we should consider improving the plugin extension to include a way to provide custom sorting

**Comment by stefanhoth** [comment]
> Perhaps we should consider improving the plugin extension to include a way to provide custom sorting

@ouchadam I think that's a bit of overkill. Instead the library should define a sensible default.

> app.db_upgrade_<oldversion_<newversion>.sql

@mattijsf What's the benefit of that format?

**Comment by mattijsf** [comment]
I'm not particularly for changing the sorting. Having a file naming convention is fine as long as it is clearly documented.

But at the same time I think it is quite easy to implement a more sensible (global) sorting that covers existing case as well. Right now it silently breaks (because the `NumberFormatException` is just returning 0) which is not right. I guess throwing a `InvalidMigrationFileNameException` (or something) would be better in that case.

@stefanhoth no clear benefit ;)

**Comment by devisnik** [comment]
Our assumption on this is very much driven by our accompanying library `sqliteprovider`, as that expects the specific naming of migrations. (see https://github.com/novoda/sqlite-provider/blob/master/core/src/main/java/novoda/lib/sqliteprovider/migration/Migrations.java#L42 )

That said, the behaviour is surely not obvious and should be properly documented.

Looking through the sources I see that [`MigrationInDir`](https://github.com/novoda/sqlite-analyzer/blob/0.3.2/analyzer/src/main/java/com/novoda/sqlite/MigrationsInDir.java) is already prepared to handle custom comparators. 

Also, the extension is prepared to host custom database connectors, see https://github.com/novoda/sqlite-analyzer/blob/0.3.2/analyzer/src/main/groovy/com/novoda/sqlite/generator/SqliteAnalyzerExtension.groovy#L47

So it should technically be possible to provide a `MigrationsConnector` using a `MigrationInDir` with a custom comparator by overriding the dbConnector` property of the extension.

**Comment by devisnik** [comment]
@mattijsf That's for pointing out this issue. 

Would be great if you could share some insights into your usage scenario (Android?) and accompanying libraries you're using. Are you using the default code generation?

**Comment by mattijsf** [comment]
We're using it in an Android application. Currently we are using sqlite with [square/sqlbrite](https://github.com/square/sqlbrite) (and it's RxJava features) as our backend. sqlite-analyzer helps us using migration scripts as leading (backend) model and writing queries ensuring safe use column / table names.

Regarding the template, we started with the FULL_ACCESS variant from:
https://github.com/novoda/sqlite-analyzer/blob/master/analyzer/src/main/groovy/com/novoda/sqlite/generator/Templates.groovy

Then we added a couple of methods:

To be able to extract specific fields from `ContentValues`
```
    public static $field.type $field.getMethod(android.content.ContentValues values) {
<% if(field.cursorType == "Blob") {%>
        return values.getAsByteArray("$field.sqlName");
<% } else { %>
        return values.getAs$field.cursorType("$field.sqlName")<% if (field.type ==~ /^(?i)boolean$/) out << " > 0" %>;
<% } %>
    }
```

To be able to create an entire object from `ContentValues`:
```
    public static $dataSet.name fromContentValues(android.content.ContentValues values) {
<% dataSet.fields.each { field -> %>
        $field.type $field.name = $field.getMethod(values);
<% } %>
        return new $dataSet.name(
<% out << dataSet.fields.collect { it.name }.join(', ') %>);
    }
```

Apart from that we're using standard code generation / configuration equal to https://github.com/novoda/sqlite-analyzer/blob/master/demo-sqliteprovider/build.gradle
